version: '3.3'
name: "library"
services:
  mysql-library:
    container_name: mysql-library
    image: mysql
    # restart: always
    environment:
      MYSQL_DATABASE: 'library'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'MyUser'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'MyPassword'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'RootRoot'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3308:3306'
    expose:
      # Opens port 3306 on the container
      - '3308'
      # Where our data will be persisted
    volumes:
      - ./mysql-library:/var/lib/mysql

volumes:
  mysql-library: